FROM maven:3.8.4-openjdk-17 AS builder
WORKDIR /autoslocos
COPY ../autoslocos/pom.xml .  
COPY ../autoslocos/src ./src  

# Run Maven command to build the project
RUN mvn clean package -DskipTests

# Execution
FROM openjdk:17-jdk-slim
WORKDIR /usr/src/app
# Copy the generated JAR file from the build stage
COPY --from=builder /autoslocos/target/*.jar app.jar
EXPOSE 8443
CMD ["java", "-jar", "app.jar"]
